module.exports = {
  env: {
    es6: true,
    node: true,
  },
  parserOptions: {
    ecmaVersion: 8,
    sourceType: "module",
    ecmaFeatures: {
      impliedStrict: true,
      experimentalObjectRestSpread: true,
    },
  },
  extends: [
    "eslint:recommended",
  ],
  rules: {
    "array-bracket-newline": ["error", "consistent"],
    "array-bracket-spacing": "error",
    "array-element-newline": ["error", "consistent"],
    "array-callback-return": ["error", { checkForEach: true }],
    "arrow-body-style": ["warn", "as-needed"],
    "arrow-parens": "error",
    "arrow-spacing": "error",
    "block-spacing": "error",
    "brace-style": "error",
    "camelcase": "warn",
    "comma-dangle": ["error", "always-multiline"],
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": "error",
    "consistent-this": ["error", "self"],
    "curly": ["warn", "multi-or-nest"],
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    "eol-last": "error",
    "eqeqeq": "error",
    "func-call-spacing": "error",
    "func-style": ["warn", "declaration"],
    "function-call-argument-newline": ["error", "consistent"],
    "function-paren-newline": ["error", "consistent"],
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "implicit-arrow-linebreak": "error",
    "indent": ["error", 2],
    "init-declarations": "warn",
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "linebreak-style": "error",
    "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
    "max-len": ["warn", { code: 120 }],
    "multiline-comment-style": "warn",
    "new-parens": "warn",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-empty-pattern": "error",
    "no-eval": "error",
    "no-extra-bind": "warn",
    "no-extra-parens": "error",
    "no-fallthrough": "off",
    "no-floating-decimal": "error",
    "no-implicit-coercion": "warn",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "warn",
    "no-loss-of-precision": "error",
    "no-multi-spaces": ["warn", { ignoreEOLComments: true}],
    "no-multi-str": "error",
    "no-multiple-empty-lines": "warn",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-octal-escape": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-template-curly-in-string": "warn",
    "no-throw-literal": "warn",
    "no-trailing-spaces": "error",
    "no-unmodified-loop-condition": "error",
    "no-unsafe-optional-chaining": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-rename": "error",
    "no-useless-return": "warn",
    "no-var": "error",
    "no-void": "error",
    "no-whitespace-before-property": "error",
    "nonblock-statement-body-position": ["error", "below"],
    "object-curly-newline": ["error", { consistent: true }],
    "object-curly-spacing": ["error", "always"],
    "object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
    "object-shorthand": "warn",
    "operator-assignment": "warn",
    "operator-linebreak": ["error", "before"],
    "padded-blocks": ["error", { blocks: "never", classes: "always", switches: "never" }],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-exponentiation-operator": "warn",
    "prefer-named-capture-group": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-object-spread": "warn",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "quote-props": ["error", "consistent-as-needed"],
    "quotes": ["error", "double", { allowTemplateLiterals: false, avoidEscape: true }],
    "rest-spread-spacing": "error",
    "semi": "error",
    "semi-spacing": "error",
    "semi-style": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", {
      anonymous: "never",
      named: "never",
      asyncArrow: "always",
    }],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "switch-colon-spacing": "error",
    "template-curly-spacing": "warn",
    "yoda": ["error", "never", { exceptRange: true }],
  },
};
