name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: |
          yarn prettier --list-different .
          yarn lint
          yarn spellcheck
